#!/usr/bin/env python3
r"""capture_repeat.py -- repeat-phase capture in Project AirSim (stage 1).

Places a non-physics drone at every waypoint of the S-route, at every
requested altitude, yawed to the route bearing, and stores one nadir frame
of the DownCamera per waypoint. The frames go to a manifest in the exact
format evaluate_ridf.py consumes (`wp`, `file`, `crop_px`, ...).

Why teleport instead of flying
------------------------------
Gaffin's agent is a kinematic camera moved over the image grid. Flying the
route with a controller would add tracking error nobody is studying; the
non-physics robot (scene_snapshot_repeat.jsonc) is placed exactly with
Robot.set_pose(), which the client API documents for non-physics vehicles.

Coordinate frames
-----------------
Route waypoints are lat/lon (generated by snapshot_lib.resample_route,
exactly as in the teach phase -- that list IS the route definition). For
placement they are converted to metres relative to the CesiumGeoreference
origin with an exact WGS84 ECEF -> ENU transform, which is precisely the
tangent frame Cesium for Unreal uses. snapshot_lib.local_xy is NOT used
here: its flat-earth constants are off by ~6 m at the 3 km distance between
the georeference origin and the route (verified against pyproj), which at
30 m altitude would be five sensor pixels of registration error.
Cesium places the georeference origin at the Unreal world origin with
+X = East, +Y = South, +Z = Up (left-handed ESU). AirSim
maps its NED frame as x -> +X, y -> +Y, z -> -Z. Consequently AirSim's
"north" axis points geographic EAST unless the CesiumGeoreference actor is
rotated in the level. `--ned-x-bearing` is the true compass bearing of
AirSim's +x axis: 90 for an unrotated georeference (default), 0 if the
actor was rotated so that +X faces north. The registration test decides:
if the RIDF minimum sits at +-90 or 180 degrees, this value is wrong.

Altitude above ground
---------------------
`--altitudes` are metres above ground (AGL), as in the teach phase. Ground
level is measured in the simulator itself: the DownCamera's planar depth
(90 deg, 256 px) is the vertical distance to everything visible in the
footprint; its 95th percentile is the deepest common surface = street
level, unaffected by a roof or tree under the nadir point. The drone is
placed at the previous ground estimate minus AGL, the depth is read, and
the height is corrected once if the measured AGL is off by more than
`--agl-tol`. Both the nominal and the measured AGL go into the manifest.

Settle
------
Cesium streams tiles asynchronously, so after every teleport the script
grabs frames until two consecutive ones are stable (mean abs grey
difference < `--settle-thresh`) and the depth image has no holes, with a
hard cap `--settle-max`. Settle time and iterations are logged per frame.

Colour order: projectairsim.utils.unpack_image returns BGR (OpenCV
convention); the frame is flipped to RGB before saving, because the sensor
chain's grey conversion (ITU-R 601) weights R and B differently.

Usage
-----
    python scripts/capture_repeat.py --route routes/route_s.csv --altitudes 50 \
        --origin-lat 52.040111 --origin-lon 8.495097 --origin-h 800 \
        --sim-config sim_config --scene scene_snapshot_repeat.jsonc \
        --out data/repeat_innenstadt \
        [--wps 0 1 2] [--teach-root data/teach_innenstadt] [--dry-run] [--resume]

--teach-root makes the script cross-check its waypoints (lat, lon,
bearing) against the teach manifest of the same altitude and abort on any
mismatch. --dry-run computes and prints all poses without touching the
simulator (works without projectairsim installed).
"""
from __future__ import annotations

import argparse
import csv
import json
import math
import sys
import time
from pathlib import Path

import numpy as np
from PIL import Image

from snapshot_lib import (ROTATION_MARGIN, footprint_from_altitude,
                          resample_route)

SENSOR_FOV_DEG = 90.0
CAMERA_ID = "DownCamera"
IMG_SCENE, IMG_DEPTH_PLANAR = 0, 1


# --------------------------------------------------------------------------
# Route (identical to extract_route_snapshots.py)
# --------------------------------------------------------------------------
def load_route_csv(path: str):
    """Read (lat, lon) pairs from a CSV; header names are matched loosely."""
    with open(path, newline="") as f:
        rows = list(csv.reader(f))
    if not rows:
        raise ValueError(f"empty route file: {path}")
    header = [c.strip().lower() for c in rows[0]]

    def col(*names):
        for n in names:
            if n in header:
                return header.index(n)
        return None

    i_lat, i_lon = col("lat", "latitude"), col("lon", "lng", "longitude")
    body = rows[1:] if i_lat is not None else rows
    if i_lat is None:
        i_lat, i_lon = 0, 1
    pts = [(float(r[i_lat]), float(r[i_lon])) for r in body if r]
    if len(pts) < 2:
        raise ValueError("route needs at least 2 points")
    return pts


def check_against_teach(wps, teach_root: Path, alt_m: float, tol_deg=1e-6,
                        tol_brg=0.01):
    """Abort if the regenerated waypoints differ from the teach manifest."""
    man = teach_root / f"alt_{alt_m:04.0f}m" / "manifest.csv"
    if not man.exists():
        print(f"  (no teach manifest at {man}; skipping cross-check)")
        return
    seen = {}
    with open(man, newline="") as f:
        for r in csv.DictReader(f):
            if float(r.get("line_offset_m", 0.0)) == 0.0:
                seen.setdefault(int(r["wp"]), r)
    n_bad = 0
    for i, w in enumerate(wps):
        t = seen.get(i)
        if t is None:
            continue
        if (abs(float(t["lat"]) - w["lat"]) > tol_deg
                or abs(float(t["lon"]) - w["lon"]) > tol_deg
                or abs(float(t["bearing_deg"]) - w["bearing_deg"]) > tol_brg):
            n_bad += 1
            if n_bad <= 3:
                print(f"  MISMATCH wp {i}: teach ({t['lat']}, {t['lon']}, "
                      f"{t['bearing_deg']}) vs here ({w['lat']:.7f}, "
                      f"{w['lon']:.7f}, {w['bearing_deg']:.2f})")
    if n_bad:
        sys.exit(f"{n_bad} waypoints differ from the teach manifest -- "
                 f"route/spacing must be identical between phases")
    print(f"  waypoints identical to teach manifest ({len(seen)} checked)")


# --------------------------------------------------------------------------
# Geometry
# --------------------------------------------------------------------------
def capture_fov_deg(sensor_fov_deg: float = SENSOR_FOV_DEG) -> float:
    return 2.0 * math.degrees(math.atan(
        ROTATION_MARGIN * math.tan(math.radians(sensor_fov_deg) / 2.0)))


# WGS84
_A = 6378137.0
_F = 1.0 / 298.257223563
_E2 = _F * (2.0 - _F)


def geodetic_to_ecef(lat_deg, lon_deg, h_m):
    la, lo = math.radians(lat_deg), math.radians(lon_deg)
    n = _A / math.sqrt(1.0 - _E2 * math.sin(la) ** 2)
    return ((n + h_m) * math.cos(la) * math.cos(lo),
            (n + h_m) * math.cos(la) * math.sin(lo),
            (n * (1.0 - _E2) + h_m) * math.sin(la))


def geodetic_to_enu(lat0, lon0, h0, lat, lon, h):
    """Exact East/North/Up metres of (lat, lon, h) in the local tangent
    frame at (lat0, lon0, h0) -- the frame Cesium for Unreal uses."""
    x0, y0, z0 = geodetic_to_ecef(lat0, lon0, h0)
    x, y, z = geodetic_to_ecef(lat, lon, h)
    dx, dy, dz = x - x0, y - y0, z - z0
    la, lo = math.radians(lat0), math.radians(lon0)
    e = -math.sin(lo) * dx + math.cos(lo) * dy
    n = (-math.sin(la) * math.cos(lo) * dx - math.sin(la) * math.sin(lo) * dy
         + math.cos(la) * dz)
    u = (math.cos(la) * math.cos(lo) * dx + math.cos(la) * math.sin(lo) * dy
         + math.sin(la) * dz)
    return e, n, u


def geo_to_ned_xy(origin_lat, origin_lon, origin_h, lat, lon,
                  ned_x_bearing_deg):
    """lat/lon -> AirSim (x, y) in metres. `ned_x_bearing_deg` is the true
    bearing of AirSim's +x axis (90 for an unrotated Cesium georeference)."""
    d_east, d_north, _ = geodetic_to_enu(origin_lat, origin_lon, origin_h,
                                         lat, lon, origin_h)
    b = math.radians(ned_x_bearing_deg)
    x = d_north * math.cos(b) + d_east * math.sin(b)
    y = -d_north * math.sin(b) + d_east * math.cos(b)
    return x, y


def bearing_to_ned_yaw_deg(bearing_deg, ned_x_bearing_deg):
    return ((bearing_deg - ned_x_bearing_deg) + 180.0) % 360.0 - 180.0


def yaw_from_quat(w, x, y, z) -> float:
    """Yaw (deg) of a w,x,y,z quaternion, ZYX convention."""
    return math.degrees(math.atan2(2 * (w * z + x * y),
                                   1 - 2 * (y * y + z * z)))


# --------------------------------------------------------------------------
# Simulator link (lazy import so --dry-run works anywhere)
# --------------------------------------------------------------------------
class SimLink:
    def __init__(self, scene: str, sim_config: str, robot_name: str):
        from projectairsim import Drone, ProjectAirSimClient, World
        from projectairsim.types import ImageType, Pose, Quaternion, Vector3
        from projectairsim.utils import rpy_to_quaternion, unpack_image
        self._Pose, self._Quat, self._Vec = Pose, Quaternion, Vector3
        self._rpy2q, self._unpack, self._ImageType = (rpy_to_quaternion,
                                                       unpack_image, ImageType)
        self.client = ProjectAirSimClient()
        self.client.connect()
        self.world = World(self.client, scene, delay_after_load_sec=2,
                           sim_config_path=sim_config)
        self.drone = Drone(self.client, self.world, robot_name)

    def close(self):
        try:
            self.client.disconnect()
        except Exception:
            pass

    def lighting_info(self) -> dict:
        """Query sky/sun state from the sim.

        OFF BY DEFAULT (--query-lighting). These two calls reach into the
        level's sky actor; with CesiumSunSky instead of the sky actor the
        plugin expects, they have been observed to take Unreal down. The
        values are static anyway -- read them from the CesiumSunSky details
        panel once and record them with --note.
        """
        info = {}
        for key, fn in (("time_of_day", self.world.get_time_of_day),
                        ("sunlight_intensity_lux",
                         self.world.get_sunlight_intensity)):
            try:
                info[key] = fn()
            except Exception as e:      # not every level exposes these
                info[key] = f"n/a ({type(e).__name__})"
        return info

    def set_pose(self, x, y, z, yaw_deg):
        w, qx, qy, qz = self._rpy2q(0.0, 0.0, math.radians(yaw_deg))
        pose = self._Pose({
            "translation": self._Vec({"x": x, "y": y, "z": z}),
            "rotation": self._Quat({"w": w, "x": qx, "y": qy, "z": qz}),
            "frame_id": "DEFAULT_ID"})
        ok = self.drone.set_pose(pose, reset_kinematics=True)
        if not ok:
            raise RuntimeError("set_pose rejected -- is the robot config "
                               "non-physics?")

    def grab(self):
        """-> (rgb uint8 HxWx3, depth float32 HxW in metres, encoding str)"""
        imgs = self.drone.get_images(CAMERA_ID, [IMG_SCENE, IMG_DEPTH_PLANAR])
        scene = imgs[IMG_SCENE]
        bgr = self._unpack(scene)
        rgb = np.ascontiguousarray(bgr[:, :, ::-1])
        depth = np.asarray(self._unpack(imgs[IMG_DEPTH_PLANAR]),
                           dtype=np.float32).reshape(
            imgs[IMG_DEPTH_PLANAR]["height"], imgs[IMG_DEPTH_PLANAR]["width"])
        return rgb, depth, str(scene.get("encoding", "?"))

    def ground_truth(self) -> dict:
        p = self.drone.get_ground_truth_pose()
        t, r = p["translation"], p["rotation"]
        return {"gt_x": round(float(t["x"]), 3), "gt_y": round(float(t["y"]), 3),
                "gt_z": round(float(t["z"]), 3),
                "gt_yaw_deg": round(yaw_from_quat(r["w"], r["x"], r["y"],
                                                  r["z"]), 2)}


# --------------------------------------------------------------------------
# Capture logic
# --------------------------------------------------------------------------
def settle_and_grab(sim: SimLink, settle_min, settle_dt, settle_max,
                    thresh, depth_min_finite):
    """Grab frames until two consecutive ones agree and the depth image is
    complete. Returns (rgb, depth, info dict)."""
    t0 = time.monotonic()
    prev = None
    n = 0
    diff = float("nan")
    while True:
        rgb, depth, enc = sim.grab()
        n += 1
        gray = rgb.astype(np.float32).mean(axis=2)
        finite = float(np.isfinite(depth).mean())
        el = time.monotonic() - t0
        if prev is not None:
            diff = float(np.abs(gray - prev).mean())
            if diff < thresh and finite >= depth_min_finite and el >= settle_min:
                return rgb, depth, dict(settle_s=round(el, 2), settle_iters=n,
                                        settle_diff=round(diff, 3),
                                        depth_finite=round(finite, 4),
                                        settled=1, encoding=enc)
        if el > settle_max:
            print(f"    WARNING: settle timeout ({el:.1f} s, diff {diff:.2f}, "
                  f"depth finite {finite:.3f}) -- keeping last frame")
            return rgb, depth, dict(settle_s=round(el, 2), settle_iters=n,
                                    settle_diff=round(diff, 3),
                                    depth_finite=round(finite, 4),
                                    settled=0, encoding=enc)
        prev = gray
        time.sleep(settle_dt)


def ground_from_depth(depth: np.ndarray, pct: float) -> float:
    """Vertical distance to the deepest common surface in the footprint."""
    d = depth[np.isfinite(depth)]
    d = d[d < 1e4]                      # float16 saturation (65504) = no hit
    if d.size == 0:
        return float("nan")
    return float(np.percentile(d, pct))


def capture_altitude(sim, wps, alt_m, out_root: Path, args, params):
    alt_dir = out_root / f"alt_{alt_m:04.0f}m"
    raw_dir = alt_dir / "raw"
    raw_dir.mkdir(parents=True, exist_ok=True)
    man_path = alt_dir / "manifest.csv"
    cap_px = int(math.ceil(args.crop_px * ROTATION_MARGIN))
    fov = capture_fov_deg()

    fields = ["wp", "s_m", "lat", "lon", "alt_m", "bearing_deg", "yaw_deg",
              "ned_x", "ned_y", "ned_z", "ned_yaw_deg", "ground_z_ned",
              "agl_measured_m", "depth_p50_m", "depth_min_m",
              "gt_x", "gt_y", "gt_z", "gt_yaw_deg",
              "settle_s", "settle_iters", "settle_diff", "depth_finite",
              "settled", "encoding", "capture_px", "capture_fov_deg",
              "crop_px", "footprint_m", "file"]

    done = set()
    if man_path.exists() and args.resume:
        with open(man_path, newline="") as f:
            done = {int(r["wp"]) for r in csv.DictReader(f)}
    new_file = not man_path.exists() or not args.resume
    f = open(man_path, "w" if new_file else "a", newline="")
    w = csv.DictWriter(f, fieldnames=fields)
    if new_file:
        w.writeheader()

    (alt_dir / "params.json").write_text(json.dumps(
        {**params, "alt_m": alt_m, "capture_px": cap_px,
         "capture_fov_deg": round(fov, 4), "crop_px": args.crop_px,
         "footprint_m": round(footprint_from_altitude(alt_m, SENSOR_FOV_DEG), 3)},
        indent=2))

    ground_z = args.ground_z0          # NED z of ground (down positive)
    t_alt = time.monotonic()
    todo = [(i, wp) for i, wp in enumerate(wps)
            if (args.wps is None or i in args.wps) and i not in done]
    print(f"== alt {alt_m:.0f} m AGL: {len(todo)} waypoints "
          f"(footprint {footprint_from_altitude(alt_m, SENSOR_FOV_DEG):.0f} m)")

    for k, (i, wp) in enumerate(todo, 1):
        x, y = geo_to_ned_xy(args.origin_lat, args.origin_lon, args.origin_h,
                             wp["lat"], wp["lon"], args.ned_x_bearing)
        yaw = bearing_to_ned_yaw_deg(wp["bearing_deg"], args.ned_x_bearing)
        rel = f"raw/w{i:05d}.png"
        row = {"wp": i, "s_m": round(wp["s_m"], 2), "lat": f"{wp['lat']:.7f}",
               "lon": f"{wp['lon']:.7f}", "alt_m": alt_m,
               "bearing_deg": round(wp["bearing_deg"], 2),
               "yaw_deg": round(wp["bearing_deg"], 2),
               "ned_x": round(x, 3), "ned_y": round(y, 3),
               "ned_yaw_deg": round(yaw, 2), "capture_px": cap_px,
               "capture_fov_deg": round(fov, 4), "crop_px": args.crop_px,
               "footprint_m": round(footprint_from_altitude(alt_m, SENSOR_FOV_DEG), 3),
               "file": rel}

        if args.dry_run:
            row.update(ned_z=round(ground_z - alt_m, 3),
                       ground_z_ned=round(ground_z, 3))
            w.writerow({k2: row.get(k2, "") for k2 in fields})
            if k <= 3 or k == len(todo):
                print(f"  wp {i:3d}  x {x:8.2f}  y {y:8.2f}  z "
                      f"{ground_z - alt_m:8.2f}  yaw {yaw:7.2f}  "
                      f"(bearing {wp['bearing_deg']:6.2f})")
            continue

        # -- place, measure ground, correct once, settle, capture ----------
        z = ground_z - alt_m
        for attempt in range(args.agl_iters):
            sim.set_pose(x, y, z, yaw)
            rgb, depth, info = settle_and_grab(
                sim, args.settle_min, args.settle_dt, args.settle_max,
                args.settle_thresh, args.depth_min_finite)
            agl_meas = ground_from_depth(depth, args.ground_pct)
            if not math.isfinite(agl_meas):
                print("    no hit -- retry from safe altitude")
                z = args.ground_z0 - 400.0
                continue
            ground_z = z + agl_meas
            if abs(agl_meas - alt_m) <= args.agl_tol:
                break
            z = ground_z - alt_m
        else:
            print(f"    note: AGL still {agl_meas:.2f} m after "
                  f"{args.agl_iters} corrections (target {alt_m})")

        Image.fromarray(rgb, "RGB").save(alt_dir / rel)
        if args.save_depth:
            np.save(alt_dir / f"raw/w{i:05d}_depth.npy", depth)
        gt = sim.ground_truth()
        fin = depth[np.isfinite(depth)]
        row.update(ned_z=round(z, 3), ground_z_ned=round(ground_z, 3),
                   agl_measured_m=round(agl_meas, 2),
                   depth_p50_m=round(float(np.median(fin)), 2) if fin.size else "",
                   depth_min_m=round(float(fin.min()), 2) if fin.size else "",
                   **gt, **info)
        w.writerow({k2: row.get(k2, "") for k2 in fields})
        f.flush()
        if k % 5 == 0 or k <= 3 or k == len(todo):
            el = time.monotonic() - t_alt
            print(f"  [{k}/{len(todo)}] wp {i:3d}  AGL {agl_meas:6.2f} m  "
                  f"settle {info['settle_s']:5.1f} s/{info['settle_iters']}  "
                  f"gt_yaw {gt['gt_yaw_deg']:7.2f}  {el / k:.1f} s/wp")
    f.close()
    return ground_z


# --------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------
def parse_args():
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--route", required=True, help="route_s.csv")
    ap.add_argument("--altitudes", type=float, nargs="+", required=True,
                    help="AGL altitudes in m (teach: 30 40 50 60 80 100 140 "
                         "200 300)")
    ap.add_argument("--spacing", type=float, default=5.0,
                    help="waypoint spacing in m -- must equal the teach run")
    ap.add_argument("--out", required=True, help="repeat output root")
    ap.add_argument("--wps", type=int, nargs="*",
                    help="subset of waypoint indices (registration test)")
    ap.add_argument("--teach-root", help="cross-check waypoints against the "
                                         "teach manifests")
    # geo <-> sim
    ap.add_argument("--origin-lat", type=float, required=True,
                    help="CesiumGeoreference origin latitude")
    ap.add_argument("--origin-lon", type=float, required=True,
                    help="CesiumGeoreference origin longitude")
    ap.add_argument("--origin-h", type=float, required=True,
                    help="CesiumGeoreference origin height (ellipsoidal, m)")
    ap.add_argument("--ned-x-bearing", type=float, default=90.0,
                    help="true bearing of AirSim +x (90: unrotated Cesium "
                         "georeference, +X=East; 0: +X=North)")
    ap.add_argument("--ground-z0", type=float, default=0.0,
                    help="initial guess of ground level in NED z (m, down "
                         "positive) = origin height - ellipsoidal ground "
                         "height; refined from depth at every waypoint. "
                         "Only saves one probe round at the first waypoint.")
    # camera
    ap.add_argument("--crop-px", type=int, default=640,
                    help="sensor crop the evaluator takes from the 906 px "
                         "capture (must match robot config: capture = "
                         "ceil(crop*sqrt2))")
    ap.add_argument("--save-depth", action="store_true",
                    help="also store the planar depth image as .npy")
    # ground / AGL
    ap.add_argument("--ground-pct", type=float, default=95.0,
                    help="depth percentile taken as ground level")
    ap.add_argument("--agl-tol", type=float, default=0.5,
                    help="accepted |measured - nominal| AGL in m")
    ap.add_argument("--agl-iters", type=int, default=3,
                    help="max place-measure-correct rounds per waypoint")
    # settle
    ap.add_argument("--settle-min", type=float, default=1.0)
    ap.add_argument("--settle-dt", type=float, default=0.7)
    ap.add_argument("--settle-max", type=float, default=25.0)
    ap.add_argument("--settle-thresh", type=float, default=0.5,
                    help="mean |grey_t - grey_t-1| (0..255) below which the "
                         "frame counts as settled")
    ap.add_argument("--depth-min-finite", type=float, default=0.995,
                    help="min fraction of finite depth pixels (tile holes)")
    # sim
    ap.add_argument("--sim-config", help="folder with the scene/robot jsonc")
    ap.add_argument("--scene", default="scene_snapshot_repeat.jsonc")
    ap.add_argument("--robot", default="Drone1")
    ap.add_argument("--resume", action="store_true",
                    help="skip waypoints already in the manifest")
    ap.add_argument("--dry-run", action="store_true",
                    help="compute poses and write manifests, no simulator")
    ap.add_argument("--query-lighting", action="store_true",
                    help="ask the sim for time-of-day and sun intensity. "
                         "Known to crash Unreal on levels using "
                         "CesiumSunSky -- leave off and use --note instead.")
    ap.add_argument("--note", default="",
                    help="free text stored in params.json (e.g. Cesium MSSE, "
                         "SunSky settings)")
    return ap.parse_args()


def main():
    args = parse_args()
    out_root = Path(args.out)
    out_root.mkdir(parents=True, exist_ok=True)

    route_pts = load_route_csv(args.route)
    wps = resample_route(route_pts, args.spacing)
    print(f"route: {len(route_pts)} points -> {len(wps)} waypoints at "
          f"{args.spacing} m; origin ({args.origin_lat}, {args.origin_lon}, "
          f"{args.origin_h} m), "
          f"AirSim +x bearing {args.ned_x_bearing} deg")
    if args.teach_root:
        check_against_teach(wps, Path(args.teach_root), args.altitudes[0])

    params = {
        "kind": "repeat-phase capture (Project AirSim, non-physics teleport)",
        "route": str(args.route), "spacing_m": args.spacing,
        "origin_lat": args.origin_lat, "origin_lon": args.origin_lon,
        "origin_h_m": args.origin_h, "geo_transform": "WGS84 ECEF -> ENU "
        "at origin (exact)", "ned_x_bearing_deg": args.ned_x_bearing,
        "sensor_fov_deg": SENSOR_FOV_DEG, "camera_id": CAMERA_ID,
        "ground_pct": args.ground_pct, "agl_tol_m": args.agl_tol,
        "settle": {"min_s": args.settle_min, "dt_s": args.settle_dt,
                   "max_s": args.settle_max, "thresh": args.settle_thresh,
                   "depth_min_finite": args.depth_min_finite},
        "scene": args.scene, "robot": args.robot, "note": args.note,
        "dry_run": args.dry_run,
    }

    sim = None
    if not args.dry_run:
        sim = SimLink(args.scene, args.sim_config, args.robot)
        if args.query_lighting:
            params["lighting"] = sim.lighting_info()
            print(f"sim connected; lighting: {params['lighting']}")
        else:
            params["lighting"] = "not queried (see note)"
            print("sim connected")
    (out_root / "params.json").write_text(json.dumps(params, indent=2))

    try:
        ground_z = args.ground_z0
        for alt in args.altitudes:
            args.ground_z0 = ground_z   # carry the ground estimate over
            ground_z = capture_altitude(sim, wps, alt, out_root, args, params)
    finally:
        if sim is not None:
            sim.close()
    print(f"done -> {out_root}")


if __name__ == "__main__":
    main()
